version: 1.0.{build}
image: Visual Studio 2017
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: Kitnws4GvXEhr47lMxsJ+IbU2n/dBTDGQNuCI3GisZSGPkWPP0yiDyHxnI/bo6Th